"""migration

Revision ID: 715798e2c505
Revises: 1c4445677464
Create Date: 2018-04-20 15:20:59.955111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715798e2c505'
down_revision = '1c4445677464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_users_usernames', table_name='users')
    op.drop_column('users', 'usernames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usernames', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_usernames', 'users', ['usernames'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
